bessst.be/run/urls.py
from datetime import date

from django.conf import settings
from django.conf.urls import patterns, include, url
from django.views.generic import TemplateView, DetailView, ListView, list_detail
from django.views.generic.simple import redirect_to
from projects.models import Project
from events.models import Event
from resources.models import Resource
from flatpages.models import FlatPage
from axis.models import Axis

from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'bessst.views.home', name='home'),
    # url(r'^bessst/', include('bessst.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    #(r'^$', TemplateView.as_view(template_name="home.html")),
    url(r'^newsletter/', include('newsletter.urls')),
    url(r'^admin/', include(admin.site.urls)),
    (r'^i18n/', include('django.conf.urls.i18n')),
)

urlpatterns += i18n_patterns('',
    url(r'^$', list_detail.object_list, {"queryset":Axis.objects.all(), 'template_name':'home.html'}, name='home'),
    url(r'^projects/$', 'projects.views.projects', name='projects'),
    url(r'^projects/(?P<slug>[\w-]+)/$', DetailView.as_view(model=Project), name='project-detail'),
    url(r'^axis/(?P<slug>[\w-]+)/$', 'projects.views.projects', name='axis-detail'),
    
    url(r'^agenda/$', list_detail.object_list, {"queryset":Event.objects.filter(published=True, end_date__gt=date.today()),}, name='agenda'),
    url(r'^agenda/archive/$', list_detail.object_list, {"queryset":Event.objects.filter(published=True, start_date__lt=date.today()), 'extra_context': {'archive': True}}, name='agenda-archive'),
    url(r'^agenda/(?P<slug>[\w-]+)/$', DetailView.as_view(model=Event), name='event-detail'),
    
    url(r'^inspiration/$', list_detail.object_list, {"queryset":Resource.objects.filter(published=True)}, name='inspiration'),
    url(r'^community/$', 'people.views.community', name='community'),
    url(r'^atlas/$', 'people.views.atlas', name='atlas'),
    url(r'^atlas/(?P<id>[0-9]+)/$', 'people.views.atlas', name='atlas'),
    url(r'^e-mail/$', 'people.views.e_mail_list', name='e_mail_list'),
    
    url(r'^label-form/$', 'people.views.label_form', name='label_form'),
    
    url(r'^(?P<slug>[\w-]+)/$', DetailView.as_view(model=FlatPage), name='flatpage-detail'),
)

# Serve asset files in DEBUG:
if settings.DEBUG:
    urlpatterns += patterns('',
        url(r'^assets/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': settings.MEDIA_ROOT,
        }),
   )

bessst.be/events/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _
from projects.models import Project
from axis.models import Axis
from django.contrib.contenttypes import generic
from media_app.models import Image

class Event(models.Model):
    published = models.BooleanField(_("Published"), default=False)
    title = models.CharField(max_length=255, verbose_name=_("Title (NL)"))
    title_fr = models.CharField(max_length=255, verbose_name=_("Title (FR)"), blank=True)
    title_en = models.CharField(max_length=255, verbose_name=_("Title (EN)"), blank=True)
    slug = models.SlugField(_("Slug"), unique=True, help_text=_("Unique identifier. Allows a constant targeting of this event."))
    project = models.ForeignKey(Project, verbose_name=_("Related project"))
    #axis = models.ForeignKey(Axis, verbose_name=_("Axis")) # only if there's no related project
    start_date = models.DateField(_("Start date"))
    end_date = models.DateField(_("End date"))
    summary = models.TextField(_("Summary (NL)"), blank=True)
    summary_fr = models.TextField(_("Summary (FR)"), blank=True)
    summary_en = models.TextField(_("Summary (EN)"), blank=True)
    description = models.TextField(_("Description (NL)"), blank=True)
    description_fr = models.TextField(_("Description (FR)"), blank=True)
    description_en = models.TextField(_("Description (EN)"), blank=True)

    location = models.CharField(max_length=80, verbose_name=_("Location (NL)"), null=True)
    location_en = models.CharField(max_length=80, verbose_name=_("Location (EN)"), blank=True, null=True)
    location_fr = models.CharField(max_length=80, verbose_name=_("Location (FR)"), blank=True, null=True)

    image_set = generic.GenericRelation(Image)

    @models.permalink
    def get_absolute_url(self):
        return ('event-detail', (), {'slug': str(self.slug)})

    def __unicode__(self):
        return self.title

    class Meta:
        ordering = ['-start_date', 'project', 'title']

bessst.be/projects/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _

from orderable.models import Orderable

from axis.models import Axis
from people.models import People
from django.contrib.contenttypes import generic
from media_app.models import Image

from random import randint

class Project(Orderable):
    published = models.BooleanField(_("Published"), default=False)
    archived = models.BooleanField(_("Archived"), default=False)

    title = models.CharField(max_length=255, verbose_name=_("Title (NL)"))
    title_en = models.CharField(max_length=255, verbose_name=_("Title (EN)"), blank=True)
    title_fr = models.CharField(max_length=255, verbose_name=_("Title (FR)"), blank=True)

    subtitle = models.CharField(max_length=255, verbose_name=_("Subtitle (NL)"), blank=True)
    subtitle_en = models.CharField(max_length=255, verbose_name=_("Subtitle (EN)"), blank=True)
    subtitle_fr = models.CharField(max_length=255, verbose_name=_("Subtitle (FR)"), blank=True)

    slug = models.SlugField(_("Slug"), unique=True, help_text=_("Unique identifier. Allows a constant targeting of this project."))
    producers = models.ManyToManyField(People, verbose_name=_("Partners"), related_name="producer_set")
    link = models.URLField(_("Link URL"), null=True, blank=True)

    location = models.CharField(max_length=80, verbose_name=_("Location (NL)"), null=True)
    location_en = models.CharField(max_length=80, verbose_name=_("Location (EN)"), blank=True, null=True)
    location_fr = models.CharField(max_length=80, verbose_name=_("Location (FR)"), blank=True, null=True)

    axis = models.ForeignKey(Axis, verbose_name=_("Axis"))

    summary = models.TextField(_("Summary (NL)"), blank=True)
    summary_en = models.TextField(_("Summary (EN)"), blank=True)
    summary_fr = models.TextField(_("Summary (FR)"), blank=True)

    description = models.TextField(_("Description (NL)"))
    description_en = models.TextField(_("Description (EN)"), blank=True)
    description_fr = models.TextField(_("Description (FR)"), blank=True)

    start_date = models.DateField(_("Start date"), blank=True, null=True)
    end_date = models.DateField(_("End date"), blank=True, null=True)
    image_set = generic.GenericRelation(Image)

#    @property
    def size_x(self):
        return randint(4, 14)
    
#    @property
    def size_y(self):
        return randint(2, 7)

    def __unicode__(self):
        return self.title

    @models.permalink
    def get_absolute_url(self):
        return ('project-detail', (), {'slug': str(self.slug)})

bessst.be/projects/views.py
# Create your views here.
from django.shortcuts import render_to_response
from django.template import RequestContext

from projects.models import Project
from axis.models import Axis

def projects(request, slug=False):
    tpl_params = {}
    tpl_params['object_list'] = Project.objects.filter(published=True)
    tpl_params['axis_list'] = Axis.objects.all()
    if slug:
        tpl_params['slug'] = slug
        tpl_params['axis'] = Axis.objects.get(slug=slug)
    return render_to_response("projects/project_list.html", tpl_params, context_instance = RequestContext(request))

bessst.be/run/views.py
from django.shortcuts import redirect

def redirect_to_local_version(request):
    return redirect('/' + request.LANGUAGE_CODE + '/')

bessst.be/run/templates/projects/project_detail.html
{% extends "base.html" %}
{% load markup i18n utils thumbnails %}

{% block title %}{% get_trans object title LANGUAGE_CODE %}{% endblock %}

{% block slug %}project{% endblock%}

{% block header %}
<h1 class="{{ object.axis.pictogram }}">{% get_trans object title LANGUAGE_CODE %} <span class='subtitle'>{% get_trans object subtitle LANGUAGE_CODE %}</span></h1>
{% endblock header%}

{% block content %}

<section id="main" class="big box">
    <div class="tail">
        {% get_trans object summary LANGUAGE_CODE %}
    </div>

    <div class="columns">
        {% get_trans object description LANGUAGE_CODE %}
    </div>
    
    {% if object.slug == "bessst-route" %}
    <iframe width="500" height="400" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.be/maps/ms?msid=216671772446348664973.0004d3e2615d74e9c0674&amp;msa=0&amp;ie=UTF8&amp;t=m&amp;ll=50.809189,4.401398&amp;spn=0.053477,0.169086&amp;output=embed"></iframe>
    {% endif %}

</section>
<section id="right">
        <dl id="metadata" class="box">
            <dt style="display: none">{% get_trans object axis LANGUAGE_CODE  %}</dt>
            <dd>
                <img class="metadata-axis" src="{{ STATIC_URL }}axis/{{ object.axis.pictogram }}.png">
            </dd>
            <dt>{% trans "Partners" %}</dt>
            <dd>
                <ul class="inline">
                {% for p in object.producers.all %}
                    <li>{% if p.link %}
                        <a href="{{ p.link }}" target="_blank">{{ p.get_full_name }}</a>
                    {% else %}
                        {{ p.get_full_name }}
                    {% endif %}
                    </li>
                {% endfor %}
                </ul>
            </dd>
            {% if object.location %}
                <dt>{% trans "Locatie" %}</dt>
                <dd>{% get_trans object location LANGUAGE_CODE %}</dd>
            {% endif %}

            {% if object.link %}
                <dt>{% trans "Project website" %}</dt>
                <dd><a href="{{ object.link }}" target="_blank">{{ object.link|slice:'7:'|truncatechars:'30' }}</a></dd>
            {% endif %}

            {% if object.event_set.all %}
                <dt>{% trans "Related events" %}</dt>
                <dd>
                    <ul>
                    {% for e in object.event_set.all %}
                        <li><a href="{{ e.get_absolute_url }}">{% get_trans e title LANGUAGE_CODE %}</a></li>
                    {% endfor %}
                    </ul>
                </dd>
            {% endif %}
        </dl>
</section>
{% endblock %}

{% block footer %}
<div id="caption-block">
    {% if object.image_set.all %}
        {% if object.image_set.count > 1 %}
        <div class="prev">
            <a href="#" style="text-decoration: none;"><img src="{{ STATIC_URL }}axis/arrow-left.png"/></a>
        </div>
        {% endif %}
        <div id="caption-list">
            {% for img in object.image_set.all %}
                <div class="caption {% if forloop.first %}visible{% endif %}" title={{ img.image.url }}>
                    {{ img }}
                </div>
            {% endfor %}
        </div>
        {% if object.image_set.count > 1 %}
        <div class="next">
            <a href="#" style="text-decoration: none;"><img src="{{ STATIC_URL }}axis/arrow-right.png"/></a>
        </div>
        {% endif %}
    {% endif %}
</div>
{% endblock %}

{% block extra_js %}
{% comment %}
    <script>
    $(document).ready(function(){
        img_h = $("img.background-image").height();
        txt_h = $("section#main").height();
        console.log(img_h)
        console.log(txt_h)
        console.log($(document).scrollTop());
        console.log($(window).height())
        //if($(document).scrollTop() == img_h) {
            // the image is higher than the text
            $(document).scroll(function(){
                console.log("scroll");
                if ($(document).scrollTop() + $(window).height() > txt_h ){
                    $("section#main").css({'position': 'fixed', 'bottom': '1em'});
                } else {
                    $("section#main").css({'position': 'static'});
                }
            });
        //} else {
            // the text is higher than the image
        //}
    });
    </script>
    {% endcomment %}
{% endblock %}

bessst.be/run/templates/projects/project_list.html
{% extends "base.html" %}
{% load markup thumbnails i18n utils %}

{% block title %}{% trans "Projecten" %}{% endblock %}

{% block slug %}projecten{% endblock%}


{% block header %}
    <div id="tooltip">&nbsp;</div>
{% endblock header%}

{% block content %}

    <section id="main">
    <div id='axis-menu'>
        {% for axis in axis_list %}
            <h2 class="logo">
                <a href='{% url axis-detail axis.slug %}'>
                    <img class="{{ axis.pictogram }} small-logo" id="{{ axis.slug }}" src="{{ STATIC_URL }}axis/{{ axis.pictogram }}.png" title="{% get_trans axis name LANGUAGE_CODE %}" data-photo="{{ axis.image_set.all.0.image.url }}" data-photo-caption="{{ axis.image_set.all.0 }}"/>
                </a>
          </h2>
        {% endfor %}
    </div>
          <ul id='project-list'>
          {% for project in object_list %}
              <li class="box {{ project.axis.slug }} no-border {% if not slug or slug == project.axis.slug %}in-grid{% endif %} {% if project.archived %}archive{% endif %}" data-sizex="18">
                  
                  <a class="many-things-link" href="{{ project.get_absolute_url }}" data-axis="{{ project.axis.slug }}">
                  
                    <div class='lettrine'>
                        {% if project.image_set.all.0.image.url %}
                            <img src="{{ project.image_set.all.0.image|thumbnail:'150x150' }}" />
                        {% else %}
                            <div class='empty-lettrine'>&nbsp;</div>
                        {% endif %}

                        <img class="{{ project.axis.pictogram }} small-logo" id="{{ project.axis.slug }}" src="{{ STATIC_URL }}axis/{{ project.axis.pictogram }}-smaller.png" title="{{ project.axis.name }}" data-photo="{{ project.axis.image_set.all.0.image.url }}" data-photo-caption="{{ project.axis.image_set.all.0 }}"/>
                    </div>
                    
                    <div> 
                        <h1>{% get_trans project title LANGUAGE_CODE %}</h1>
                    </div>
                   
                    {% filter truncatewords_html:60 %}{% get_trans project summary LANGUAGE_CODE %}{% endfilter %}
                 
                    </a>
                    
              </li>
          {% endfor %}
          {% for axis in axis_list %}
              <li class="box axis {{ axis.slug }}" data-sizex="18">
                  <h1>{{ axis }}</h1>
                  <div class="">
                      {{ axis.description|safe }}
                  </div>
              </li>
          {% endfor %}
          </ul>
    </section>
    <div id="box-oproep">
        <a href='{% url label_form %}'>{% trans "vraag het<br /> bessst-label aan" %}</a>
    </div>
{% endblock content %}





{% block footer %}
{% endblock %}


{% block extra_js %}
    <script src="{{ STATIC_URL }}js/index.js"></script>    
    <script>
        /* If this is a project category page, the variable slug will be set.
         * If it is the general project page, it will be unset */
        var slug = '{{ slug }}';
        
        /* This function is called by the router to switch between different project categories */
        var switchTo = function(ctx) {
            var axis = ctx.params.axis;
            // we are only finished if both hiding the old is done and showing the new is done
            var finished = { hiding: false, showing: false }
            // hide the old
            $('ul#project-list .in-grid').not('.' + axis).removeClass("in-grid masonry-brick").fadeOut('fast', function() {
                finished.hiding = true;
                if (finished.showing) {
                    $('#project-list').masonry('reload');
                }
            });
            // show the new
            $('ul#project-list .' + axis).addClass("in-grid").fadeIn('fast', function() {
                finished.showing = true;
                if (finished.hiding) {
                    $('#project-list').masonry('reload');
                }
            });
            // (we don’t know which one finishes first, so we check in both cases. When both are done we trigger the masonry)
        }
        
        if (slug) {
            // hide projects not in this category
            $('ul#project-list .in-grid').not('.' + slug).removeClass("in-grid").hide();
        } else {
            // hide the later elements 
            $('ul#project-list .in-grid').slice(9).removeClass("in-grid").hide();
            var expanded = false;
        }
        
        /* For the general project  page, if we get almost to the bottom,
         we show also the remaining items */
        if (!slug) {
           $(window).bind('scroll',
               function(e){
                     console.log($(this).scrollTop())
                    if ( $(this).scrollTop() + $(window).height() > $(document).height() - 200 ) {
                        console.log("within 200px!");
                        if (!expanded) {
                            console.log("expand!");
                            expanded = true;
                            $('ul#project-list li:not(.axis)').slice(9).addClass("in-grid").fadeIn('fast', function() {
                                $('#project-list').masonry('reload');
                            });
                        /* This cant be here it would be fired too often (scroll event)
                         * 
                          // CENTER AXIS ICON IN LETTRINE SPACE
                            $('.lettrine .small-logo').each(function(){
                                this_top = 20 + $(this).parent().height()/2 - $(this).height()/2;
                                this_left = 20 + $(this).parent().width()/2 - $(this).width()/2;
                                $(this).css({'top': this_top + 'px', 'left': this_left + 'px'});
                            });*/
                            
                        }
                    }
                }
           );
        }
        /* Show axis names and colours on axis-image rollover
         * (except for the boxes that contain axis info, they always keep their colour)
         */
        $(".logo").hover(function(e){
            picto = $( "img", $(this));
            filename = picto.attr("src").slice(0, -4);
            picto.attr("src", filename + "_c.png");
            
            $("#tooltip").text(picto.attr('title')).css('visibility','visible').addClass(picto.attr('class'));
            $("#tooltip").css('left', e.pageX);
            $("#tooltip").css('top', e.pageY);
            
            $("." + picto.attr("id")).removeClass("no-border");
        
        }, function(){
            picto.attr("src", filename + ".png");
            
            $("#tooltip").html("&nbsp;").css('visibility','hidden').removeClass();
            $("." + picto.attr("id") + ':not(.axis)').addClass("no-border");
        
        });
        
        /* ROLLOVER PROJECT BOX (not for axis box) */
        $('ul#project-list li:not(.axis)').hover(function(){
            $(this).removeClass('no-border');
            $('.lettrine .small-logo' ,$(this)).hide()
            }, function(){
            $(this).addClass('no-border');
            $('.lettrine .small-logo' ,$(this)).show()
        });
        
        
        /* if the Browser supports the HTML5 History API we use client side 
         routing for smooth transition inbetween the different axis categories! */
        if ( window.history && window.history.replaceState ) {
            page('/:langs/axis/:axis/', switchTo);
            page.start();
        }
        
        // these functions need all images loaded
        $(window).load(function() {
            
            // do the masonry and establish its settings
            $('#project-list').masonry({
                itemSelector: 'li.in-grid',
                columnWidth: 30,
                isAnimated: true,
                  animationOptions: {
                    duration: 750,
                    easing: 'swing',
                    queue: false
                  }
                
            });
            
          
        // CENTER AXIS ICON IN LETTRINE SPACE
            $('.lettrine .small-logo').each(function(){
                this_top = 20 + $(this).parent().height()/2 - $(this).height()/2;
                this_left = 20 + $(this).parent().width()/2 - $(this).width()/2;
                $(this).css({'top': this_top + 'px', 'left': this_left + 'px'});
            });
        
        });
    </script>
{% endblock %}