bessst.be/run/urls.py
from datetime import date

from django.conf import settings
from django.conf.urls import patterns, include, url
from django.views.generic import TemplateView, DetailView, ListView, list_detail
from django.views.generic.simple import redirect_to
from projects.models import Project
from events.models import Event
from resources.models import Resource
from flatpages.models import FlatPage
from axis.models import Axis

from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'bessst.views.home', name='home'),
    # url(r'^bessst/', include('bessst.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    #(r'^$', TemplateView.as_view(template_name="home.html")),
    url(r'^newsletter/', include('newsletter.urls')),
    url(r'^admin/', include(admin.site.urls)),
    (r'^i18n/', include('django.conf.urls.i18n')),
)

urlpatterns += i18n_patterns('',
    url(r'^$', list_detail.object_list, {"queryset":Axis.objects.all(), 'template_name':'home.html'}, name='home'),
    url(r'^projects/$', 'projects.views.projects', name='projects'),
    url(r'^projects/(?P<slug>[\w-]+)/$', DetailView.as_view(model=Project), name='project-detail'),
    url(r'^axis/(?P<slug>[\w-]+)/$', 'projects.views.projects', name='axis-detail'),
    
    url(r'^agenda/$', list_detail.object_list, {"queryset":Event.objects.filter(published=True, end_date__gt=date.today()),}, name='agenda'),
    url(r'^agenda/archive/$', list_detail.object_list, {"queryset":Event.objects.filter(published=True, start_date__lt=date.today()), 'extra_context': {'archive': True}}, name='agenda-archive'),
    url(r'^agenda/(?P<slug>[\w-]+)/$', DetailView.as_view(model=Event), name='event-detail'),
    
    url(r'^inspiration/$', list_detail.object_list, {"queryset":Resource.objects.filter(published=True)}, name='inspiration'),
    url(r'^community/$', 'people.views.community', name='community'),
    url(r'^atlas/$', 'people.views.atlas', name='atlas'),
    url(r'^atlas/(?P<id>[0-9]+)/$', 'people.views.atlas', name='atlas'),
    url(r'^e-mail/$', 'people.views.e_mail_list', name='e_mail_list'),
    
    url(r'^label-form/$', 'people.views.label_form', name='label_form'),
    
    url(r'^(?P<slug>[\w-]+)/$', DetailView.as_view(model=FlatPage), name='flatpage-detail'),
)

# Serve asset files in DEBUG:
if settings.DEBUG:
    urlpatterns += patterns('',
        url(r'^assets/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': settings.MEDIA_ROOT,
        }),
   )

bessst.be/people/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.template.defaultfilters import slugify
from django.db import IntegrityError

class People(models.Model):
    name = models.CharField(max_length=255, verbose_name=_("Name"))
    prefix = models.CharField(max_length=255, verbose_name=_("Prefix"), null=True, blank=True)
    slug = models.SlugField(_("Slug"), unique=True, help_text=_("Unique identifier. Allows a constant targeting of this event."))
    #country = 
    address = models.CharField(max_length=100, verbose_name=_("Address"), null=True, blank=True)
    city = models.CharField(max_length=80, verbose_name=_("Postal code + City"), null=True, blank=True)
    phone = models.CharField(max_length=20, verbose_name=_("Phone number"), null=True, blank=True)
    email = models.EmailField(max_length=100, verbose_name=_("Email"), null=True, blank=True)
    link = models.URLField(_("Link URL"), null=True, blank=True)
    biography = models.TextField(_("Short biography (NL)"), blank=True)
    biography_en = models.TextField(_("Short biography (EN)"), blank=True)
    biography_fr = models.TextField(_("Short biography (FR)"), blank=True)

    def __unicode__(self):
        return self.name

    class Meta:
        ordering = ['name']

    def get_full_name(self):
        try:
            return self.individual.get_full_name()
        except:
            return self.__unicode__()

    def save(self, *args, **kwargs):
        if self.slug == "":
            self.slug = slugify(self.get_full_name())
        while True:
            try:
                super(People, self).save(*args, **kwargs)
                break
            except IntegrityError:
                self.slug += '-extra'
                

class Individual(People):
    firstname = models.CharField(max_length=255, verbose_name=_("First Name"), null=True, blank=True)

    def get_full_name(self):
        fullname = ""
        if self.firstname: fullname += self.firstname + u' '
        if self.prefix: fullname += self.prefix + u' '
        if self.name: fullname += self.name
        return fullname

    def __unicode__(self):
        return self.get_full_name()

class Organization(People):
    contact_person = models.ForeignKey(Individual, verbose_name=_("Contact Person"), related_name="contact_person", null=True, blank=True)
    individuals = models.ManyToManyField(Individual, verbose_name=_("Individuals"), related_name="individual_set", blank=True)
    def __unicode__(self):
        return self.name


class Friend(Individual):
    location_latitude = models.FloatField(verbose_name=_("Latitude of my Silence Location"))
    location_longitude = models.FloatField(verbose_name=_("Longitude of my Silence Location"))
    location_explanation = models.TextField(_("Explanation of my Silence Location"))
    newsletter = models.BooleanField(verbose_name=_("Receive Newsletter"))
    display = models.BooleanField(verbose_name=_("Display my name"), default=True)
        
    def __unicode__(self):
        return self.get_full_name()

bessst.be/people/views.py
# Create your views here.
import json

from django.shortcuts import render_to_response
from django.template import RequestContext
from django import forms
from django.forms import ModelForm
from django.forms.models import inlineformset_factory
from django.template.defaultfilters import slugify
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.decorators import login_required

from people.models import Individual, Friend, Organization
from projects.models import Project
from flatpages.models import FlatPage

class IndividualForm(ModelForm):
    class Meta:
        model = Friend
        fields = ('location_explanation', 'firstname', 'prefix', 'name', 'email', 'link', 'location_latitude', 'location_longitude', 'newsletter', 'display')

class OrganizationForm(ModelForm):
    class Meta:
        model = Organization
        fields = ('name', 'address', 'city', 'phone', 'email', 'link')
    description = forms.CharField(label=_('Description of the Project'), widget=forms.Textarea)
    existing_partners = forms.CharField(label=_('Existing Partners'), widget=forms.Textarea)
    channels = forms.CharField(label=_('Through which channels can you already communicate?'), widget=forms.Textarea)

    def save(self, force_insert=False, force_update=False, commit=True):
        m = super(OrganizationForm, self).save(commit=False)
        
        # also create a new project that lists the aanvraag
        title = "Bessst label aanvraag " + self.cleaned_data['name']
        project = Project(published=False, axis_id=1, title=title)
        project.description += self.cleaned_data['description']
        project.description += '\n<h2>Existing Partners</h2>'
        project.description += '\n<p>' + self.cleaned_data['existing_partners'] + '</p>'
        project.description += '\n<h2>Through which channels can you already communicate?</h2>'
        project.description += self.cleaned_data['channels']
        project.slug = slugify(title)
        project.save()
        
        if commit:
            m.save()
        return m

def community(request):
    tpl_params = {}
    
    tpl_params['object_list'] = []
    
    # Because friends are a subclass of individuals,
    # We have to weed them out here:
    individuals = Individual.objects.all()
    for i in individuals:
        try:
            f = i.friend
        except Individual.DoesNotExist:
            tpl_params['object_list'].append(i)

    tpl_params['partners'] = Organization.objects.all()
    tpl_params['text'] = FlatPage.objects.get(slug='community')
    return render_to_response("people/individual_list.html", tpl_params, context_instance = RequestContext(request))

@login_required
def e_mail_list(request):
    tpl_params = {}
    return render_to_response("people/e_mail_list.html", { 'object_list' : Friend.objects.filter(newsletter=True) }, context_instance = RequestContext(request) )

def label_form(request):
    tpl_params = {}
    tpl_params['submitted'] = False

    if request.method == 'POST': # If the form has been submitted...
        form = OrganizationForm(request.POST) # A form bound to the POST data
        if form.is_valid():
            form.save()
            tpl_params['submitted'] = True
    else:
        form = OrganizationForm()
    tpl_params['form'] = form
    return render_to_response("people/label_form.html", tpl_params, context_instance = RequestContext(request))

def atlas(request, id=None):
    tpl_params = {}
    
    friends = Friend.objects.all().order_by('-location_latitude')
    
    # Prepare a JSON hash with which we draw all the friends on the map
    # client-side
    friends_hash = []
    for f in friends:
        hash = { 'name' : False, 'explanation' : f.location_explanation, 'lat' : f.location_latitude, 'lng' : f.location_longitude }
        if f.display:
            hash['name'] = f.get_full_name()
        friends_hash.append(hash)

    tpl_params['friends_json'] = json.dumps(friends_hash, indent=2, ensure_ascii=False)
    if request.method == 'POST': # If the form has been submitted...
        form = IndividualForm(request.POST) # A form bound to the POST data
        if form.is_valid():
            form.save()
            tpl_params['submitted'] = True
    else:
        form = IndividualForm(label_suffix='')
    tpl_params['form'] = form
    return render_to_response("people/atlas.html", tpl_params, context_instance = RequestContext(request))

def label_form(request):
    tpl_params = {}
    tpl_params['submitted'] = False

    if request.method == 'POST': # If the form has been submitted...
        form = OrganizationForm(request.POST) # A form bound to the POST data
        if form.is_valid():
            form.save()
            tpl_params['submitted'] = True
    else:
        form = OrganizationForm(label_suffix='')
    tpl_params['form'] = form
    return render_to_response("people/label_form.html", tpl_params, context_instance = RequestContext(request))

bessst.be/run/views.py
from django.shortcuts import redirect

def redirect_to_local_version(request):
    return redirect('/' + request.LANGUAGE_CODE + '/')

bessst.be/run/templates/people/atlas.html
{% extends "base.html" %}
{% load markup i18n utils %}

{% block title %}Atlas{% endblock %}

{% block slug %}atlas{% endblock %}


{% block content %}
<section id='main'>
<div class="box" data-sizex="35">
    <h2>{% trans "Bessst atlas" %}</h2>
    <div id="map"></div>
</div>
</div>
    
<div class="box" data-sizex="16">
    <h2 id="silence-friend">{% trans "Apply as a silence friend" %}</h2>
    <p class="explanation"><img id="place-dragger" src="http://cdn.leafletjs.com/leaflet-0.5/images/marker-icon.png"/>{% trans "Drag pin on to the map to share your favourite silence location in Brussels" %}</p>
    {% if not submitted%}
    <form action="{% url atlas %}" method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit" />
    </form>
    {% else %}
    <p>{% trans "Thanks for your application as a silence friend." %}</p>
    {% endif %}
</div>

</Section>
{% endblock %}

{% block extra_js %}
<script src="{{STATIC_URL}}js/jquery-ui-1.8.23.custom.min.js"></script>
<link rel="stylesheet" href="http://cdn.leafletjs.com/leaflet-0.5/leaflet.css" />
 <!--[if lte IE 8]>
     <link rel="stylesheet" href="http://cdn.leafletjs.com/leaflet-0.5/leaflet.ie.css" />
 <![endif]-->
 <script src="http://cdn.leafletjs.com/leaflet-0.5/leaflet.js"></script>
<script>

/* Map interactions*/

// create a map in the "map" div, set the view to a given place and zoom
var map = L.map('map').setView([50.84694973844825, 4.354920387268066], 12);

// add an OpenStreetMap tile layer
L.tileLayer('http://{s}.tile.osm.org/{z}/{x}/{y}.png', {
    attribution: '&copy; <a href="http://osm.org/copyright">OpenStreetMap</a> deelnemers'
}).addTo(map);

/* Plot all the friends on the map */
var friends = {{ friends_json|safe }}

for (var i=0; i < friends.length; i++) {
    var friend = friends[i]
    //console.log(friend)
    friendHTML = '<p>' + friend.explanation + '</p>';
    if (friend.name) {
        friendHTML = '<h3>' + friend.name + '</h3>' + friendHTML;
    }
    var friendMarker = L.marker([friend.lat, friend.lng]).addTo(map) //These markers don’t move
        .bindPopup(friendHTML)
        .on('mouseover', function(evt) {
            evt.target.openPopup();
            })
        .on('mouseout', function(evt){
            evt.target.closePopup();
        })
        // this is a hack, making sure the view of the map moves to includes all the marks
       .openPopup()
       .closePopup();
}

var marker;

var setLatLng = function(latlng) {
        $("#id_location_latitude").val(latlng.lat);
        $("#id_location_longitude").val(latlng.lng);
        //console.log(latlng.toString());
}

/* We have a pre-existing icon, that when dragged into the map, becomes a marker on that map */

$("#place-dragger").draggable( {
    stop: function(ev,ui) {
            //console.log("stopped!");
            c = map.mouseEventToContainerPoint( ev );
            if (c.x < 0 || c.y < 0 || c.x > $(map._container).width() || c.y > $(map._container).height()) {
                //console.log("outside!")
            } else {
                var latlng = map.mouseEventToLatLng( ev );
                
                /* Calling setLatLng will fill in the hidden form fields that are submitted to the server */
                setLatLng(latlng);
                
                /* create the marker */
                marker = L.marker(latlng, { draggable : true }).addTo(map)
                .bindPopup('Dit is mijn stilteplek')
                .openPopup()
                .on('dragend', function(e) { 
                     setLatLng(e.target.getLatLng());
                     e.target.openPopup();
                });
                $(this).remove(); // remove the original element
            }
        },
});

/* Form error checking */

if ($("p:has('#id_location_latitude')").prev().hasClass("errorlist")) {
    /* This means the form is giving errors about missing the latitude,
    which means nothing was selected on the map. We need to display errors next to the map. */
    $("p:has('#id_location_latitude','#id_location_longitude')").prev().hide();
    $("p.explanation").prepend('<span class="errorlist">Om u aan te melden als stiltevriend, vragen wij u een stilteplek aan te geven. </span>')
}

</script>
{% endblock %}

bessst.be/run/templates/people/e_mail_list.html
{% extends "base.html" %}
{% load markup i18n utils thumbnails %}

{% block title %}Lijst met e-mails{% endblock %}

{% block slug %}e_mail_list{% endblock%}

{% block content %}
<pre style="margin-top: 100px;">
{% for friend in object_list%}{{friend.get_full_name}} &lt;{{friend.email}}&gt;, {% endfor%}
</pre>
{% endblock %}

bessst.be/run/templates/people/individual_list.html
{% extends "base.html" %}
{% load markup i18n utils %}

{% block title %}{% trans "Community" %}{% endblock %}

{% block slug %}community{% endblock %}


{% block content %}
<section id='main'>
<div class="big box">
    <h2>Stiltepartners</h2>
    <div class="columns">
    <ul> 
        {#{% regroup object_list|dictsort:'individual.individual_set' by individual_set as partner_list %}#}
        {% for organization in partners %}
            <li>
                {% if organization.link %}<a href="{{ organization.link }}" target="_blank">{% endif %}
                {{ organization.get_full_name }}
                {% if organization.link %}</a>{% endif %}

                {% if organization.individuals.all %}
                    <ul class='inline member-list'>
                    {% for member in organization.individuals.all %}<li>{{ member }}</li>{% endfor %}
                    </ul>
                {% endif %}
            </li>
        {% endfor %}
    </ul>
    <ul>
    </div>
        {% for individual in object_list %}
            {% if not individual.individual_set.all %}
                <li>{{ individual }}
            {% endif %}
        {% endfor %}
    </ul>
</div>

<div class="box" data-sizex="15">
    {% get_trans text content LANGUAGE_CODE %}
</div>

</section>
<div id="box-oproep">
    <a href='{% url label_form %}'>{% trans "vraag het<br /> bessst-label aan" %}</a>
</div>
{% endblock %}

bessst.be/run/templates/people/label_form.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}Label Form{% endblock %}

{% block slug %}label{% endblock %}

{% block footer %}
{% endblock %}

{% block content %}
<section id='main'>
    <div class="box">
        <h2>{% trans "Demand bessst label" %}</h2>
        {% if not submitted %}
            <form action="{% url label_form %}" method="post">{% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Submit" />
            </form>
        {% else %}
            <p>{% trans "Thank you for your bessst label demand" %}</p>
        {% endif %}
    </div>
</section>
{% endblock %}