bessst.be/run/urls.py
from datetime import date

from django.conf import settings
from django.conf.urls import patterns, include, url
from django.views.generic import TemplateView, DetailView, ListView, list_detail
from django.views.generic.simple import redirect_to
from projects.models import Project
from events.models import Event
from resources.models import Resource
from flatpages.models import FlatPage
from axis.models import Axis

from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'bessst.views.home', name='home'),
    # url(r'^bessst/', include('bessst.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    #(r'^$', TemplateView.as_view(template_name="home.html")),
    url(r'^newsletter/', include('newsletter.urls')),
    url(r'^admin/', include(admin.site.urls)),
    (r'^i18n/', include('django.conf.urls.i18n')),
)

urlpatterns += i18n_patterns('',
    url(r'^$', list_detail.object_list, {"queryset":Axis.objects.all(), 'template_name':'home.html'}, name='home'),
    url(r'^projects/$', 'projects.views.projects', name='projects'),
    url(r'^projects/(?P<slug>[\w-]+)/$', DetailView.as_view(model=Project), name='project-detail'),
    url(r'^axis/(?P<slug>[\w-]+)/$', 'projects.views.projects', name='axis-detail'),
    
    url(r'^agenda/$', list_detail.object_list, {"queryset":Event.objects.filter(published=True, end_date__gt=date.today()),}, name='agenda'),
    url(r'^agenda/archive/$', list_detail.object_list, {"queryset":Event.objects.filter(published=True, start_date__lt=date.today()), 'extra_context': {'archive': True}}, name='agenda-archive'),
    url(r'^agenda/(?P<slug>[\w-]+)/$', DetailView.as_view(model=Event), name='event-detail'),
    
    url(r'^inspiration/$', list_detail.object_list, {"queryset":Resource.objects.filter(published=True)}, name='inspiration'),
    url(r'^community/$', 'people.views.community', name='community'),
    url(r'^atlas/$', 'people.views.atlas', name='atlas'),
    url(r'^atlas/(?P<id>[0-9]+)/$', 'people.views.atlas', name='atlas'),
    url(r'^e-mail/$', 'people.views.e_mail_list', name='e_mail_list'),
    
    url(r'^label-form/$', 'people.views.label_form', name='label_form'),
    
    url(r'^(?P<slug>[\w-]+)/$', DetailView.as_view(model=FlatPage), name='flatpage-detail'),
)

# Serve asset files in DEBUG:
if settings.DEBUG:
    urlpatterns += patterns('',
        url(r'^assets/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': settings.MEDIA_ROOT,
        }),
   )

bessst.be/media_app/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes import generic

class Image(models.Model):
    description = models.CharField(max_length=255, verbose_name=_("Caption"))
    image = models.ImageField(upload_to="images", max_length=100, verbose_name=_("Image file"))
    content_type = models.ForeignKey(ContentType)
    object_id = models.PositiveIntegerField()
    content_object = generic.GenericForeignKey()

    def __unicode__(self):
        return self.description

class Document(models.Model):
    description = models.CharField(max_length=255, verbose_name=_("Caption"))
    document = models.FileField(upload_to="documents", max_length=100, verbose_name=_("Document File"))
    content_type = models.ForeignKey(ContentType)
    object_id = models.PositiveIntegerField()
    content_object = generic.GenericForeignKey()

    def __unicode__(self):
        return self.description

bessst.be/run/views.py
from django.shortcuts import redirect

def redirect_to_local_version(request):
    return redirect('/' + request.LANGUAGE_CODE + '/')

bessst.be/run/templates/analytics-partial.html
<!-- Piwik -->
<script type="text/javascript">
  var _paq = _paq || [];
  _paq.push(["trackPageView"]);
  _paq.push(["enableLinkTracking"]);

  (function() {
    var u=(("https:" == document.location.protocol) ? "https" : "http") + "://var.schr.fr/piwik/";
    _paq.push(["setTrackerUrl", u+"piwik.php"]);
    _paq.push(["setSiteId", "5"]);
    var d=document, g=d.createElement("script"), s=d.getElementsByTagName("script")[0]; g.type="text/javascript";
    g.defer=true; g.async=true; g.src=u+"piwik.js"; s.parentNode.insertBefore(g,s);
  })();
</script>
<!-- End Piwik Code -->

bessst.be/run/templates/base.html
{% load i18n thumbnails %}
<!DOCTYPE html>
<html>
<head>
    <link rel="icon" type="image/png" href="http://bessst.be/static/images/favicon.png" />
    <link rel="shortcut icon" type="image/x-icon" href="http://bessst.be/static/images/favicon.ico" />

{% load compress %}
{% if COMPRESS_ENABLED %}
{% compress css %}
    <link rel="stylesheet" type="text/less" media="all" href="{{ STATIC_URL }}less/style.less">
{% endcompress %}
{% else %}
    <link rel="stylesheet/less" type="text/css" media="all" href="{{ STATIC_URL }}less/style.less">
    <script src="{{ STATIC_URL }}less-1.3.0.min.js"></script>
{% endif%}
    <script src="{{ STATIC_URL }}jquery.min.js"></script>
    <script src="{{ STATIC_URL }}/js/jquery.masonry.min.js"></script>
    <script src="{{ STATIC_URL }}js/jquery-ui-1.8.23.custom.min.js"></script>
    <script src="{{ STATIC_URL }}js/jquery.tailing.js"></script>
    <title>{% trans "BESSST - Brussels, Heritage and Silence" %} - {% block title %}{% endblock %}</title>
</head>
<body class="{% block slug %}base{% endblock %}">
{% block nav %}
<nav>
    <ul id="logo">
        <li><a href="/"><img src="{{ STATIC_URL }}images/logo-plain.png" /></a></li>
    </ul>
    <ul id="navi">
        <li><a id="menu-projects" href="{% url projects %}">{% trans "Projects" %}</a></li>
        <li><a id="menu-agenda" href="{% url agenda %}">{% trans "Calendar" %}</a></li>
        <li><a id="menu-community" href="{% url community %}">{% trans "Community" %}</a></li>        
        <li><a id="menu-inspiratie" href="{% url inspiration %}">{% trans "Inspiration" %}</a></li>
        <li><a id="menu-over" href="{% url flatpage-detail slug="over" %}">{% trans "About" %}</a></li>
        <li><a id="menu-inspiratie" href="{% url atlas %}">{% trans "Atlas" %}</a></li>

    </ul>
    <form action="/i18n/setlang/" method="post">
        {% csrf_token %}
        <input name="next" type="hidden" value="{{ request.session.no_lang_path }}" />
        {% get_language_info_list for LANGUAGES as languages %}
        <ul id="lan">
        {% for language in languages %}
            <li class='{% if LANGUAGE_CODE == language.code %}selected{% endif %}'><button name="language" value="{{ language.code }}">{{ language.code }}</button></li>
        {% endfor %}
        </ul>
    </form>
</nav>

{% endblock %}


<div id="container">
    
    <header>
        {%  block header %}
        {%  endblock %}
    </header>

    {%  block content %}
        <section id="main">
        </section>
    {%  endblock %}
</div>

<figure id="background">
    {% block background %}
        {% if object.axis %}
            <div id="background-gradient" style="background-image: url('{{ STATIC_URL }}axis/{{ object.axis.pictogram }}-gradient.png');"></div> 
            {% if object.image_set.all.0.image %}
                <img class="background-image" src="{{ object.image_set.all.0.image|thumbnail:'1200w' }}" style="width: 100%;"/>
            {% endif %}
        {% else %}
            <div id="background-gradient" style="background-image: url('{{ STATIC_URL }}axis/all-gradient.png');"></div> 
            <!--<img class="background-image" src="{{ MEDIA_URL }}images/Waerbeke_vlinder_s.jpg" style="width: 100%;"/>-->
        {% endif %}
    {% endblock %}
</figure>



<footer>
{% block footer %}
    <div id='caption-block'>
        {% if object.image_set.all %}
            {% if object.image_set.count > 1 %}
            <div class="prev">
                <a href="#" style="text-decoration: none;"><img src="{{ STATIC_URL }}axis/arrow-left.png"/></a>
            </div>
            {% endif %}
            <div id="caption-list">
                {% for img in object.image_set.all %}
                    <div class="caption {% if forloop.first %}visible{% endif %}" title={{ img.image.url }}>
                        {{ img }}
                    </div>
                {% endfor %}
            </div>
            {% if object.image_set.count > 1 %}
            <div class="next">
                <a href="#" style="text-decoration: none;"><img src="{{ STATIC_URL }}axis/arrow-right.png"/></a>
            </div>
            {% endif %}
        {% endif %}
    </div>
{% endblock %}
</footer>


<script>
    $(window).load(function(){
        // hover on logo
        $('#logo').hover(function(){
            $('img', $(this)).attr('src', '{{ STATIC_URL }}images/logo.png');
            }, function(){
            $('img', $(this)).attr('src', '{{ STATIC_URL }}images/logo-plain.png');
        });
        
        // show where we are
        $("#navi li a").each(function() {
            if ( $(this).attr('href') == document.location.pathname ) { 
                $(this).addClass("selected");
            };
        });
    
        // Toggle boxes when hovering caption box
        $("footer div#caption-list").hover(function(){
                $("section").css("visibility", "hidden");
                $("header").hide();
                $("#background-gradient").hide();
            }, function(){
                $("section").css("visibility", "visible");
                $("header").show();
                $("#background-gradient").show();
        });
        // Navigate through images
        $("footer div.prev").click(function(){
            current = $("div.caption.visible");
            current.removeClass("visible")
            if (current.prev().hasClass("caption")){
                current.prev().addClass("visible");
                $(".background-image").attr("src", current.prev().attr("title"));
            } else {
                last = $("div#caption-list div.caption:last-child").addClass("visible");
                last.addClass("visible");
                $(".background-image").attr("src", last.attr("title"));
            }
        });
        $("footer div.next").click(function(){
            current = $("div.caption.visible");
            current.removeClass("visible")
            if (current.next().hasClass("caption")){
                current.next().addClass("visible");
                $(".background-image").attr("src", current.next().attr("title"));
            } else {
                first = $("div#caption-list div.caption:first-child")
                first.addClass("visible");
                $(".background-image").attr("src", first.attr("title"));
            }
        });

        // applies "Tailing/Queue de lampe" filter
        $(".tail").tailing();

    });
    $(window).resize(function(){
        if ($('.tail-space').length > 0) {
            $('.tail-space').delete();
        }
        $(".tail").tailing();
    });
    

</script>

{% block extra_js %}
{% endblock %}

{% include "analytics-partial.html" %}
</body>
</html>

bessst.be/run/templates/home.html
{% extends "base.html" %}
{% load i18n utils thumbnails %}

<title>{% trans "BESSST - Brussels, Heritage and Silence" %} - {% block title %}{% endblock %}</title>

{% block slug %}home{% endblock%}

{% block content %}
<section>
<div id="axis-list">
    {% for axis in object_list %}
    <div class='axis-home' title="{{ axis.name }}">
        <a href="{% url axis-detail slug=axis.slug %}">
        <img class= "{{ axis.pictogram }} smaller-logo" id="{{ axis.slug }}" src="/static/axis/{{ axis.pictogram }}-smaller.png" title="{{ axis.name }}" />
        {% get_trans axis name LANGUAGE_CODE %}
        </a>
    </div>
    {% endfor %}
</div>
</section>
{% endblock %}


{% block background %}
    {% for axis in object_list %}
    <img class="background-image home-axis-image" id="background-{{ axis.slug }}" src="{{ axis.image_set.all.0.image|thumbnail:'1200w' }}" />
    {% endfor %}
{% endblock %}

{% block footer %}
<div id="caption-block">
    <div id="home-caption-list">
        {% for axis in object_list %}
            <div class="caption" title={{ axis.image_set.all.0.image.url }}>
                {{ axis.image_set.all.0.description }}
            </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

{% block extra_js %}
    <script>
        var photos = {
	        slide: function(){
                current_axis = $("div.axis-home:visible");
                current_caption = $("div.caption:visible");
                current_img = $("img.home-axis-image:visible");
                $(current_img).fadeOut(2000);
                $(current_axis).slideUp(500);
                $(current_caption).slideUp(500);

                if (current_axis.next().hasClass("axis-home")){
                    next_axis = current_axis.next();
                } else {
                    next_axis = $("div#axis-list div.axis-home:first-child")
                }
                if (current_caption.next().hasClass("caption")){
                    next_caption = current_caption.next();
                } else {
                    next_caption = $("div#home-caption-list div.caption:first-child")
                }
                if (current_img.next().hasClass("home-axis-image")){
                    next_img = current_img.next();
                } else {
                    next_img = $("figure#background img.home-axis-image:first-child")
                }
                $(next_img).delay(500).fadeIn(2000);
                $(next_axis).delay(2000).slideDown(500);
                $(next_caption).delay(2000).slideDown(500);
	        }
        }

        $(window).load(function() {
            $('.axis-home').each(function(){
                left = $(document).width()/2 - $(this).width()/2 ;
                $(this).css('left', left + 'px');
            });
            // Toggle boxes when hovering caption box
            $("footer div#home-caption-list").hover(function(){
                    $("section").css("visibility", "hidden");
                    $("header").hide();
                    $("#background-gradient").hide();
                }, function(){
                    $("section").css("visibility", "visible");
                    $("header").show();
                    $("#background-gradient").show();
            });
            photos.slide()
            window.setInterval(function() { photos.slide(); }, 5000);
        });

    </script>
{% endblock %}